---
- name: install git
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python-setuptools
    - python3-setuptools
    - python3-wheel
    - python3-pip


- name: check out master branch
  git:
    repo: 'https://github.com/ansible/awx'
    dest: /srv/awx
    version: devel

- name: Upgrade pip to the last version
  pip:
    name: pip
    virtualenv: /srv/aws/virtualenv
    virtualenv_command: /usr/bin/python3 -m venv

- name: Install ansible
  pip:
    name: ansible==2.7.10
    virtualenv: /srv/aws/virtualenv
    virtualenv_command: /usr/bin/python3 -m venv

    #install ansible
    #ansible-playbook -i inventory install.yml
